// Comprehensive list of AI-telltale words and phrases that AI detectors flag.
// These must NEVER appear in generated text.

export const BANNED_PHRASES: string[] = [
  // Single words commonly overused by AI
  'delve',
  'crucial',
  'pivotal',
  'nuanced',
  'multifaceted',
  'holistic',
  'paradigm',
  'synergy',
  'leverage',
  'leveraging',
  'leveraged',
  'facilitate',
  'utilize',
  'comprehensive',
  'robust',
  'cutting-edge',
  'groundbreaking',
  'transformative',
  'innovative',
  'underscore',
  'underscores',
  'navigate',
  'navigating',
  'encompasses',
  'embark',
  'realm',
  'landscape',
  'tapestry',
  'beacon',
  'testament',
  'cornerstone',
  'underpinning',
  'juxtaposition',
  'interplay',
  'fostering',
  'harnessing',
  'spearheading',
  'streamlining',
  'bolstering',
  'captivating',
  'commendable',
  'noteworthy',
  'meticulous',
  'intricate',
  'bustling',
  'aligns',
  'undeniably',
  'arguably',
  'notably',

  // Transition phrases AI overuses — student NEVER uses these
  'however',
  'moreover',
  'furthermore',
  'additionally',
  'consequently',
  'nevertheless',
  'notwithstanding',
  'in conclusion',
  'to summarize',
  'in summary',
  'in essence',
  'in light of',
  'in the context of',
  'with regard to',
  'pertaining to',
  'in terms of',
  'on the other hand',

  // Hedging and filler phrases
  "it's important to note that",
  "it should be noted that",
  "it's worth noting that",
  "it is worth mentioning",
  "it is imperative",
  "it is essential to",
  "it goes without saying",
  "it is important to",
  "it is clear that",
  "this suggests that",
  "it can be argued",
  "plays a key role",
  "needless to say",
  "one cannot overstate",

  // AI-typical phrasing patterns
  "in today's world",
  "in today's society",
  "in today's rapidly evolving",
  "in the realm of",
  "in the landscape of",
  "at the forefront of",
  "the intricacies of",
  "the complexities of",
  "a testament to",
  "serves as a reminder",
  "shed light on",
  "sheds light on",
  "the ever-changing landscape",
  "the ever-evolving",
  "plays a crucial role",
  "plays a pivotal role",
  "a myriad of",
  "a plethora of",
  "the aforementioned",
  "as previously mentioned",
  "this is particularly important because",

  // Overly formal or robotic closings
  "in this essay, I will",
  "this essay will explore",
  "this paper aims to",
  "this report will examine",
  "as we have seen",
  "as discussed above",
  "as outlined above",

  // ALL contractions — student NEVER uses contractions
  "don't",
  "doesn't",
  "didn't",
  "isn't",
  "aren't",
  "wasn't",
  "weren't",
  "can't",
  "couldn't",
  "won't",
  "wouldn't",
  "shouldn't",
  "hasn't",
  "haven't",
  "hadn't",
  "it's",
  "that's",
  "there's",
  "here's",
  "what's",
  "who's",
  "they're",
  "we're",
  "you're",
  "I'd",
  "I'm",
  "I've",
  "I'll",
  "he's",
  "she's",
  "let's",
  "they've",
  "we've",
  "you've",
  "they'd",
  "we'd",
  "you'd",
];

// Words to use sparingly (max once per 500 words)
export const LIMIT_PHRASES: string[] = [
  'significant',
  'substantial',
  'fundamental',
  'demonstrates',
  'illustrates',
  'highlights',
  'emphasizes',
  'suggests',
  'indicates',
  'reveals',
  'therefore',
  'such as',
];

// Replacement map for programmatic post-processing
export const PHRASE_REPLACEMENTS: Record<string, string> = {
  'furthermore': 'also',
  'moreover': 'also',
  'additionally': 'also',
  'however': '',
  'nevertheless': '',
  'consequently': 'as a result',
  'utilize': 'use',
  'facilitate': 'support',
  'comprehensive': 'full',
  'robust': 'strong',
  'crucial': 'important',
  'pivotal': 'important',
  'innovative': 'new',
  'transformative': 'major',
  'leverage': 'use',
  'leveraging': 'using',
  'leveraged': 'used',
  'holistic': 'complete',
  'multifaceted': 'complex',
  'nuanced': 'detailed',
  'fostering': 'supporting',
  'encompasses': 'includes',
  'navigate': 'manage',
  'navigating': 'managing',
  'delve': 'examine',
  'embark': 'start',
  'noteworthy': 'important',
  'meticulous': 'careful',
  'intricate': 'complex',
  'arguably': '',
  'undeniably': '',
  'notably': '',
  'notwithstanding': 'despite',
  'in conclusion': '',
  'to summarize': '',
  'in summary': '',
  'in essence': '',
  'in light of': 'based on',
  'in the context of': 'in',
  'with regard to': 'about',
  'pertaining to': 'about',
  'in terms of': 'for',
  'on the other hand': '',
};

export function getBannedPhrasesPromptBlock(): string {
  return `ABSOLUTELY BANNED WORDS AND PHRASES - Never use any of these:
${BANNED_PHRASES.map(p => `- "${p}"`).join('\n')}

USE SPARINGLY (maximum once per 500 words):
${LIMIT_PHRASES.map(p => `- "${p}"`).join('\n')}`;
}
